development:
  dialect: postgres
  database: login_development
  user: abhay
  password: abhay@123
  host: 127.0.0.1
  pool: 5

test:
  dialect: postgres
  database: login_test
  user: abhay
  password: abhay@123
  host: 127.0.0.1
  pool: 5

production:
  dialect: postgres
  database: login_production
  user: abhay
  password: abhay@123
  host: 127.0.0.1
  pool: 5
